
<? $this->headTitle('Bienvenido') ?>

  <div class="row">
 
      <h3>Portal</h3>
      
      <?=$this->semaforo(rand(1,100))?>
      <?=$this->semaforo(rand(1,100))?>
      <?=$this->semaforo(rand(1,100))?>
      <?=$this->semaforo(rand(1,100))?>
      <?=$this->semaforo(rand(1,100))?>
      <?=$this->semaforo(rand(1,100))?>
      <?=$this->semaforo(rand(1,100))?>
      <?=$this->semaforo(rand(1,100))?>
      
  </div>