<div class="row">
    <h1>Admin</h1>
    
    <ul>
        <li>
            <a href="<?=$this->url('admin/default',array('controller'=>'categoria','action'=>'index'))?>">Categoría link 1</a>
        </li>
        <li>
            <a href="<?=$this->url('mantcategoria')?>">Categoría link 2</a>
        </li>
    </ul>

    
    <h1>Menu</h1>
    
    
    
    <ul>
        <? if($acl->puedo('ver','sysconfig')):?>
            <li><a href="#">System Config</a></li>
        <? endif; ?>
        <? if($acl->puedo('agregar','bus')):?>
            <li><a href="#">Agregar Bus</a></li>
        <? endif; ?>
        <? if($acl->puedo('agregar','chofer')):?>
            <li><a href="#">Agregar Chofer</a></li>
        <? endif; ?>
        <? if($acl->puedo('postergar','venta')):?>
            <li><a href="#">Posetergar Pasaje</a></li>
        <? endif; ?>
        <? if($acl->puedo('crear','venta')):?>
            <li><a href="#">Vender Pasaje</a></li>
        <? endif; ?>
        <? if($acl->puedo('ver-reporte-semanal','venta')):?>
            <li><a href="#">Ver Reporte Ventas Semanal</a></li>
        <? endif; ?>
        <? if($acl->puedo('ver-reporte-anual','venta')):?>
            <li><a href="#">Ver Reporte Ventas Anual</a></li>
        <? endif; ?>
    </ul>
    
</div>
