<div class="row">
    
    <table id="tblProveedores" class="table table-striped table-bordered table-hover table-condensed">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Ruc</th>
                <th>Correo</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->rows as $row): ?>
                <tr>
                    <td><?=$row->getNombre()?></td>
                    <td><?=$row->getRuc()?></td>
                    <td><?=$row->getEmail()?></td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
    
</div>

<script type="text/javascript">
window.print();
</script>